name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.19.1]

    env:
      NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: pnpm install
    - run: pnpm run build
    - name: Change Directory
      run: cd /home/uton/actions-runner/_work/capstonelatest/capstonelatest
    - run: pm2 restart 0
